name: Build Scan Push

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: saiyada/hello-devops

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $env:IMAGE_NAME:latest .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      - name: Push to DockerHub
        run: docker push $env:IMAGE_NAME:latest